# Generated by Django 5.2.1 on 2025-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='map_zoom_level',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='geofence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='usersearch',
            name='results_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('building', 'Building'), ('classroom', 'Classroom'), ('office', 'Office'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('parking', 'Parking'), ('entrance', 'Entrance'), ('facility', 'Facility'), ('landmark', 'Landmark'), ('dormitory', 'Dormitory'), ('lab', 'Laboratory'), ('study_room', 'Study Room'), ('restaurant', 'Restaurant'), ('food_court', 'Food Court'), ('lecture_hall', 'Lecture Hall'), ('security', 'Security')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smsalert',
            name='alert_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('password_reset', 'Password Reset'), ('geofence_entry', 'Geofence Entry'), ('geofence_exit', 'Geofence Exit'), ('navigation', 'Navigation'), ('welcome', 'Welcome'), ('profile_update', 'Profile Update'), ('password_changed', 'Password Changed'), ('notification', 'General Notification')], max_length=20),
        ),
    ]
