# Generated by Django 5.2.1 on 2025-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_customuser_map_zoom_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
