# Generated by Django 5.2.3 on 2025-06-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_adminnotification_recommendation_media_url_and_more'),
        ('navigation', '0003_recommendation_media_url'),
    ]

    operations = [
    ]
