# Generated by Django 5.2.1 on 2025-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_adminnotification_usernotificationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="search_type",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
