# Generated by Django 5.2.1 on 2025-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0005_usersearch_search_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationroute",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description for this route.", null=True
            ),
        ),
        migrations.AddField(
            model_name="navigationroute",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this route currently active and usable?"
            ),
        ),
        migrations.AddField(
            model_name="navigationroute",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name for this route (e.g., 'Main Library to Block A')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationroute",
            name="distance",
            field=models.FloatField(help_text="in meters"),
        ),
        migrations.AlterField(
            model_name="navigationroute",
            name="estimated_time",
            field=models.IntegerField(help_text="in minutes"),
        ),
        migrations.AlterField(
            model_name="navigationroute",
            name="is_accessible",
            field=models.BooleanField(
                default=True,
                help_text="Is this route accessible for users with disabilities?",
            ),
        ),
    ]
