# Generated by Django 5.2.1 on 2025-06-28 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0006_navigationroute_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusPath",
            fields=[
                (
                    "path_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the campus path (e.g., 'Main Entrance to Library Path')",
                        max_length=255,
                    ),
                ),
                (
                    "area_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Identifier for the area this path belongs to, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the path."
                    ),
                ),
                (
                    "geojson_feature",
                    models.JSONField(
                        help_text="GeoJSON feature data for this path, including LineString geometry and properties."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campus Path",
                "verbose_name_plural": "Campus Paths",
                "ordering": ["area_id", "name"],
            },
        ),
        migrations.AlterField(
            model_name="smsalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("password_reset", "Password Reset"),
                    ("geofence_entry", "Geofence Entry"),
                    ("geofence_exit", "Geofence Exit"),
                    ("navigation", "Navigation"),
                    ("welcome", "Welcome"),
                    ("profile_update", "Profile Update"),
                    ("password_changed", "Password Changed"),
                    ("notification", "General Notification"),
                    ("campus_direction", "Campus Direction"),
                ],
                max_length=20,
            ),
        ),
    ]
